### ISSUE TITLE
Regarding releasing training code

### ISSUE THREAD

**Issue by jpan72** [QQ-MM/Video-CCAM#12]
Hello Authors,

Thanks for publishing this great work!
Do you have any plan to release the training code?

**Comment by Jaron123s** [comment]
Sorry for the slow progress of organizing the code. If you just want to fine-tune it, we recommend using the [xtuner](https://github.com/InternLM/xtuner) framework for fine-tuning. Thank you for your support and we will let you know if there's any progress.
