### ISSUE TITLE
AssertionError: Wrong input formats

### ISSUE THREAD

**Issue by jqXiong** [QQ-MM/Video-CCAM#5]
Traceback (most recent call last):
  File "/home/zippo/Video-CCAM/demo.py", line 23, in <module>
    response = mllm.generate(texts=[question], videos=[frames])[0]
  File "/home/zippo/Video-CCAM/model/videoccam.py", line 297, in generate
    assert len(et) == 2, f'Wrong input formats for {t}'
AssertionError: Wrong input formats for hello

**Comment by jqXiong** [comment]
No matter how I change the question, I will get this error.

**Comment by zd11024** [comment]
I encounter this problem too. Maybe for inference, we need to concatenate the text with `DEFAULT_VIDEO_TOKEN`. I find the following line at `evaluate.py`
```
texts=['\n'.join([DEFAULT_VIDEO_TOKEN, t]) for t in data['text'][0]],
```

**Comment by Jaron123s** [comment]
Sorry for not replying in time. You encounter the problem in sample reference code, right? As @zd11024 says, prepending `DEFAULT_VIDEO_TOKEN` before the question can fix this problem.
