### ISSUE TITLE
Testing VideoVista

### ISSUE THREAD

**Issue by YunxinLi** [QQ-MM/Video-CCAM#6]
We have tested your model on our video Benchmark ([VideoVista](https://videovista.github.io/)), which achieved a superior performance.

Yet, we did not see the paper address corresponding to your model Video-CCAM.

When are you going to release it?  Could we discuss it further?

Best,
Yunxin Li
E-mail: liyunxin987@163.com

**Comment by Jaron123s** [comment]
Thank you for your evaluation on our work! Currently, the project is still undergoing revisions and there is no clear timeline for the release of the paper. Once the model's performance has been improved to a satisfactory level, we will release the paper and open-source all the training code and training data.
