### ISSUE TITLE
ValueError: SiglipVisionModel does not support Flash Attention 2.0 yet.

### ISSUE THREAD

**Issue by LeeChuh** [QQ-MM/Video-CCAM#8]
When loading the visual encoder (SigLip model), I got the error below:

`ValueError: SiglipVisionModel does not support Flash Attention 2.0 yet.`

Is there a way to fix this?

**Comment by Jaron123s** [comment]
Flash Attention 2.0 support for SigLIPVisionModel is added in `transformers>=4.43.0`. So you can either upgrade the `transformers` or comment out this [line](https://huggingface.co/JaronTHU/Video-CCAM-4B-v1.1/blob/main/modeling_videoccam.py#L60) in the `modeling_videoccam.py` file.
