### ISSUE TITLE
 For short or incomplete responses, some are abandoned while the others are rephrased into long and complete sentences by GPT-4o-mini [35] and Gemini 1.5 Flash [45

### ISSUE THREAD

**Issue by xmy0916** [QQ-MM/Video-CCAM#9]
could you please share this prompt used by gpt4o?

**Comment by Jaron123s** [comment]
@xmy0916 Sure! "Please rephrase the given caption to a complete and comprehensive sentence:\nCaption: {<original_caption>}\nPlease only generate the rephrased sentence."
